name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn run build

      - name: Configure Git
        run: |
          git config --global user.email "youngyu19@gmail.com"
          git config --global user.name "Young Yu"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/youngbryanyu/youngbryanyu.github.io.git

      - name: Deploy to GitHub Pages
        run: yarn run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
